# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emby_status.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Home_Tab = QtWidgets.QWidget()
        self.Home_Tab.setAutoFillBackground(False)
        self.Home_Tab.setObjectName("Home_Tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Home_Tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_about = QtWidgets.QGroupBox(self.Home_Tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_about.setFont(font)
        self.groupBox_about.setAutoFillBackground(False)
        self.groupBox_about.setStyleSheet("QGroupBox{\n"
"    padding-top: 25px;\n"
"     margin-top: -20px;\n"
"}")
        self.groupBox_about.setTitle("")
        self.groupBox_about.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_about.setObjectName("groupBox_about")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_about)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_users = QtWidgets.QLabel(self.groupBox_about)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_users.setFont(font)
        self.label_users.setAlignment(QtCore.Qt.AlignCenter)
        self.label_users.setObjectName("label_users")
        self.gridLayout_6.addWidget(self.label_users, 2, 0, 1, 1)
        self.label_total_tv = QtWidgets.QLabel(self.groupBox_about)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_total_tv.setFont(font)
        self.label_total_tv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_tv.setObjectName("label_total_tv")
        self.gridLayout_6.addWidget(self.label_total_tv, 2, 1, 1, 1)
        self.label_active_devices = QtWidgets.QLabel(self.groupBox_about)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_active_devices.setFont(font)
        self.label_active_devices.setAutoFillBackground(False)
        self.label_active_devices.setAlignment(QtCore.Qt.AlignCenter)
        self.label_active_devices.setObjectName("label_active_devices")
        self.gridLayout_6.addWidget(self.label_active_devices, 4, 0, 1, 1)
        self.label_total_movies = QtWidgets.QLabel(self.groupBox_about)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_total_movies.setFont(font)
        self.label_total_movies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_movies.setObjectName("label_total_movies")
        self.gridLayout_6.addWidget(self.label_total_movies, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_about, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.Home_Tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 764, 310))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollAreaWidgetContents_2.setFont(font)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 4, 0, 1, 1)
        self.label_server_name = QtWidgets.QLabel(self.Home_Tab)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_server_name.setFont(font)
        self.label_server_name.setScaledContents(False)
        self.label_server_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_server_name.setObjectName("label_server_name")
        self.gridLayout_2.addWidget(self.label_server_name, 0, 0, 1, 1)
        self.label_version = QtWidgets.QLabel(self.Home_Tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_version.setFont(font)
        self.label_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_version.setObjectName("label_version")
        self.gridLayout_2.addWidget(self.label_version, 1, 0, 1, 1)
        self.label_NowPlaying = QtWidgets.QLabel(self.Home_Tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_NowPlaying.setFont(font)
        self.label_NowPlaying.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NowPlaying.setObjectName("label_NowPlaying")
        self.gridLayout_2.addWidget(self.label_NowPlaying, 3, 0, 1, 1)
        self.tabWidget.addTab(self.Home_Tab, "")
        self.Users_Tab = QtWidgets.QWidget()
        self.Users_Tab.setEnabled(True)
        self.Users_Tab.setObjectName("Users_Tab")
        self.verticalLayout_UserTab = QtWidgets.QVBoxLayout(self.Users_Tab)
        self.verticalLayout_UserTab.setObjectName("verticalLayout_UserTab")
        self.users_tab_label = QtWidgets.QLabel(self.Users_Tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.users_tab_label.setFont(font)
        self.users_tab_label.setAlignment(QtCore.Qt.AlignCenter)
        self.users_tab_label.setObjectName("users_tab_label")
        self.verticalLayout_UserTab.addWidget(self.users_tab_label)
        self.scrollArea_Users = QtWidgets.QScrollArea(self.Users_Tab)
        self.scrollArea_Users.setWidgetResizable(True)
        self.scrollArea_Users.setObjectName("scrollArea_Users")
        self.scrollAreaWidgetContents_users = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_users.setGeometry(QtCore.QRect(0, 0, 764, 456))
        self.scrollAreaWidgetContents_users.setObjectName("scrollAreaWidgetContents_users")
        self.verticalLayout_UsersScroll = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_users)
        self.verticalLayout_UsersScroll.setObjectName("verticalLayout_UsersScroll")
        self.scrollArea_Users.setWidget(self.scrollAreaWidgetContents_users)
        self.verticalLayout_UserTab.addWidget(self.scrollArea_Users)
        self.tabWidget.addTab(self.Users_Tab, "")
        self.device_tab = QtWidgets.QWidget()
        self.device_tab.setObjectName("device_tab")
        self.verticalLayout_DeviceTab = QtWidgets.QVBoxLayout(self.device_tab)
        self.verticalLayout_DeviceTab.setObjectName("verticalLayout_DeviceTab")
        self.devices_tab_label = QtWidgets.QLabel(self.device_tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.devices_tab_label.setFont(font)
        self.devices_tab_label.setAlignment(QtCore.Qt.AlignCenter)
        self.devices_tab_label.setObjectName("devices_tab_label")
        self.verticalLayout_DeviceTab.addWidget(self.devices_tab_label)
        self.scrollArea_Devices = QtWidgets.QScrollArea(self.device_tab)
        self.scrollArea_Devices.setWidgetResizable(True)
        self.scrollArea_Devices.setObjectName("scrollArea_Devices")
        self.scrollAreaWidgetContents_Devices = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Devices.setGeometry(QtCore.QRect(0, 0, 764, 456))
        self.scrollAreaWidgetContents_Devices.setObjectName("scrollAreaWidgetContents_Devices")
        self.verticalLayout_Devices = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_Devices)
        self.verticalLayout_Devices.setObjectName("verticalLayout_Devices")
        self.scrollArea_Devices.setWidget(self.scrollAreaWidgetContents_Devices)
        self.verticalLayout_DeviceTab.addWidget(self.scrollArea_Devices)
        self.tabWidget.addTab(self.device_tab, "")
        self.SystemInfo_Tab = QtWidgets.QWidget()
        self.SystemInfo_Tab.setObjectName("SystemInfo_Tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SystemInfo_Tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_SystemInfo = QtWidgets.QGroupBox(self.SystemInfo_Tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_SystemInfo.setFont(font)
        self.groupBox_SystemInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_SystemInfo.setObjectName("groupBox_SystemInfo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_SystemInfo)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_Connection = QtWidgets.QGroupBox(self.groupBox_SystemInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_Connection.setFont(font)
        self.groupBox_Connection.setAutoFillBackground(True)
        self.groupBox_Connection.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Connection.setObjectName("groupBox_Connection")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Connection)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Wan = QtWidgets.QLabel(self.groupBox_Connection)
        self.label_Wan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Wan.setObjectName("label_Wan")
        self.verticalLayout_4.addWidget(self.label_Wan)
        self.label_Lan = QtWidgets.QLabel(self.groupBox_Connection)
        self.label_Lan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lan.setObjectName("label_Lan")
        self.verticalLayout_4.addWidget(self.label_Lan)
        self.gridLayout_3.addWidget(self.groupBox_Connection, 1, 1, 1, 1)
        self.groupBox_Version = QtWidgets.QGroupBox(self.groupBox_SystemInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_Version.setFont(font)
        self.groupBox_Version.setAutoFillBackground(True)
        self.groupBox_Version.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Version.setObjectName("groupBox_Version")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Version)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ServerVersion = QtWidgets.QLabel(self.groupBox_Version)
        self.label_ServerVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ServerVersion.setObjectName("label_ServerVersion")
        self.verticalLayout_2.addWidget(self.label_ServerVersion)
        self.label_HasUpdate = QtWidgets.QLabel(self.groupBox_Version)
        self.label_HasUpdate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HasUpdate.setObjectName("label_HasUpdate")
        self.verticalLayout_2.addWidget(self.label_HasUpdate)
        self.label_PendinRestart = QtWidgets.QLabel(self.groupBox_Version)
        self.label_PendinRestart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PendinRestart.setObjectName("label_PendinRestart")
        self.verticalLayout_2.addWidget(self.label_PendinRestart)
        self.gridLayout_3.addWidget(self.groupBox_Version, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_SystemInfo)
        self.groupBox_MoreInfo = QtWidgets.QGroupBox(self.SystemInfo_Tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_MoreInfo.setFont(font)
        self.groupBox_MoreInfo.setAutoFillBackground(True)
        self.groupBox_MoreInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_MoreInfo.setObjectName("groupBox_MoreInfo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_MoreInfo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_OperatingSystem = QtWidgets.QLabel(self.groupBox_MoreInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_OperatingSystem.setFont(font)
        self.label_OperatingSystem.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OperatingSystem.setObjectName("label_OperatingSystem")
        self.gridLayout_4.addWidget(self.label_OperatingSystem, 0, 0, 1, 1)
        self.label_LogPath = QtWidgets.QLabel(self.groupBox_MoreInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_LogPath.setFont(font)
        self.label_LogPath.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LogPath.setObjectName("label_LogPath")
        self.gridLayout_4.addWidget(self.label_LogPath, 1, 0, 1, 1)
        self.label_CachePath = QtWidgets.QLabel(self.groupBox_MoreInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_CachePath.setFont(font)
        self.label_CachePath.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CachePath.setObjectName("label_CachePath")
        self.gridLayout_4.addWidget(self.label_CachePath, 1, 1, 1, 1)
        self.label_ProgramDataPath = QtWidgets.QLabel(self.groupBox_MoreInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ProgramDataPath.setFont(font)
        self.label_ProgramDataPath.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ProgramDataPath.setObjectName("label_ProgramDataPath")
        self.gridLayout_4.addWidget(self.label_ProgramDataPath, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_MoreInfo)
        self.tabWidget.addTab(self.SystemInfo_Tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Emby Status"))
        self.label_users.setText(_translate("MainWindow", "Users: "))
        self.label_total_tv.setText(_translate("MainWindow", "Tv Shows: "))
        self.label_active_devices.setText(_translate("MainWindow", "Active Devices: "))
        self.label_total_movies.setText(_translate("MainWindow", "Movies: "))
        self.label_server_name.setText(_translate("MainWindow", "Server Name"))
        self.label_version.setText(_translate("MainWindow", "Version: "))
        self.label_NowPlaying.setText(_translate("MainWindow", "Now Playing: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home_Tab), _translate("MainWindow", "Home"))
        self.users_tab_label.setText(_translate("MainWindow", "Users"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Users_Tab), _translate("MainWindow", "Users"))
        self.devices_tab_label.setText(_translate("MainWindow", "Devices"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.device_tab), _translate("MainWindow", "Devices"))
        self.groupBox_SystemInfo.setTitle(_translate("MainWindow", "Server Name"))
        self.groupBox_Connection.setTitle(_translate("MainWindow", "Connection"))
        self.label_Wan.setText(_translate("MainWindow", "Wan Address:"))
        self.label_Lan.setText(_translate("MainWindow", "Lan Address: "))
        self.groupBox_Version.setTitle(_translate("MainWindow", "Version"))
        self.label_ServerVersion.setText(_translate("MainWindow", "Version"))
        self.label_HasUpdate.setText(_translate("MainWindow", "Has Update"))
        self.label_PendinRestart.setText(_translate("MainWindow", "Pending Restart"))
        self.groupBox_MoreInfo.setTitle(_translate("MainWindow", "Server Info"))
        self.label_OperatingSystem.setText(_translate("MainWindow", "Operating System"))
        self.label_LogPath.setText(_translate("MainWindow", "Log Path"))
        self.label_CachePath.setText(_translate("MainWindow", "Cache Path"))
        self.label_ProgramDataPath.setText(_translate("MainWindow", "ProgramDataPath"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SystemInfo_Tab), _translate("MainWindow", "System Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
